'''bb slots must be attributed by aa_bucket_parts column order, not the file
name's. FALSIFIER: file-name order blames every bb contact on the sidechain
slot's resname, silently. Why: private/project_planning/session_bioiso_notes.md.'''
import os
import numpy as np
import pytest
from ligand_vdgs.identify_bioisosteres.common import load_bucket_counts
from vacuity import assert_discriminates

def _no_bare_bb_part(keys):
    return 'bb' not in {part for k in keys for part in k.split('_')}

def _make_bucket(lib_dir, cg_label, fname, aa_bucket_parts, resname_rows):
    '''Write <lib>/<cg>/nr_vdgs/1/pos/<fname> plus a completed <cg>_log; one
    resname_rows tuple per cluster, so column layout is stated not inferred.
    DR-61: buckets live one level deeper, under a charge-sign subdirectory.'''
    frag_dir = os.path.join(lib_dir, cg_label)
    npz_dir = os.path.join(frag_dir, 'nr_vdgs', '1')
    os.makedirs(os.path.join(npz_dir, 'pos'), exist_ok=True)
    np.savez(os.path.join(npz_dir, 'pos', fname),
             aa_bucket_parts=np.asarray(aa_bucket_parts, dtype='U4'),
             cluster_id=np.arange(1, len(resname_rows) + 1, dtype=np.int32),
             cluster_num_parents=np.ones(len(resname_rows), dtype=np.int32),
             nr_scrr_resname=np.asarray(resname_rows, dtype='U4'))
    with open(os.path.join(frag_dir, f'{cg_label}_log'), 'w') as fh:
        fh.write('some generation output\nJob completed.\n')
    return npz_dir

def _attribute_by_column(parts, resname_rows, bb_col):
    '''What a reader taking its bb slot from `bb_col` returns -- used only to
    show a fixture can tell right from wrong, not a reference implementation.'''
    counts = {}
    for row in resname_rows:
        labels = list(parts)
        labels[bb_col] = row[bb_col] + '-bb'
        key = '_'.join(sorted(labels))
        counts[key] = counts.get(key, 0) + 1
    return counts

def test_bb_column_is_attributed_to_its_own_slot(tmp_path):
    '''ASP_bb: bb is slot 1, so donors come from column 1.'''
    parts = ['ASP', 'bb']
    rows = [('ASP', 'GLY'), ('ASP', 'TRP'), ('ASP', 'GLY')]
    counts, extras = load_bucket_counts(
        _make_bucket(str(tmp_path), 'CG_mixed', 'ASP_bb.npz', parts, rows),
        bb_mode='per-residue')
    assert counts == {'ASP_GLY-bb': 2, 'ASP_TRP-bb': 1}, counts
    assert extras == {'X': 0, 'noncanonical_bb': 0}, extras
    # Non-vacuity: bb is not column 0, and column 0 gives a different answer.
    assert parts.index('bb') == 1
    assert _attribute_by_column(parts, rows, 0) != counts

def test_attribution_follows_aa_bucket_parts_not_the_file_name(tmp_path):
    '''Name says ASP_bb, array says bb_ASP: the reader must follow the array.
    Unreachable from today's writer; pins which field is authoritative.'''
    fname_parts, slot_parts = ['ASP', 'bb'], ['bb', 'ASP']
    rows = [('GLY', 'ASP'), ('TRP', 'ASP'), ('GLY', 'ASP')]
    counts, _ = load_bucket_counts(
        _make_bucket(str(tmp_path), 'CG_reordered', 'ASP_bb.npz', slot_parts, rows),
        bb_mode='per-residue')
    assert counts == {'ASP_GLY-bb': 2, 'ASP_TRP-bb': 1}, counts
    # Non-vacuity: the orders really differ, and the file-name order ERASES the
    # GLY/TRP distinction into one key rather than merely permuting it.
    assert slot_parts != fname_parts
    by_name = _attribute_by_column(fname_parts, rows, fname_parts.index('bb'))
    assert by_name == {'ASP_ASP-bb': 3}, by_name

def test_two_bb_slots_fan_out_per_donor(tmp_path):
    '''bb_bb: both slots deconvolute; a homogeneous pair keeps its own name,
    which calc_aa_pair_propensities needs for symmetry_factor 1 vs 2.'''
    rows = [('ALA', 'TRP'), ('TRP', 'ALA'), ('ALA', 'ALA')]
    counts, extras = load_bucket_counts(
        _make_bucket(str(tmp_path), 'CG_bbbb', 'bb_bb.npz', ['bb', 'bb'], rows),
        bb_mode='per-residue')
    assert counts == {'ALA-bb_TRP-bb': 2, 'ALA-bb_ALA-bb': 1}, counts
    assert extras == {'X': 0, 'noncanonical_bb': 0}, extras
    # Non-vacuity, exercised in both directions: a first-slot-only reader leaves a
    # literal 'bb' part behind, and the shipped `'bb_' not in k.replace('-bb','')`
    # form accepted exactly that string (DR-49 addendum 1). The counterexample is
    # GENERATED by the wrong reader rather than written out -- a hand-picked string
    # is only as good as the guess behind it (directive: known limit).
    assert_discriminates(_no_bare_bb_part, [tuple(counts)],
                         [tuple(_attribute_by_column(['bb', 'bb'], rows, 0))], 'bb slots')

def test_noncanonical_donor_is_dropped_not_counted(tmp_path):
    '''MSE has no background frequency, so the row is not an observation: it
    goes to extras and never into counts, which would have no prior for it.'''
    rows = [('ASP', 'GLY'), ('ASP', 'MSE'), ('ASP', 'GLY')]
    counts, extras = load_bucket_counts(
        _make_bucket(str(tmp_path), 'CG_mse', 'ASP_bb.npz', ['ASP', 'bb'], rows),
        bb_mode='per-residue')
    assert counts == {'ASP_GLY-bb': 2}, counts
    assert extras == {'X': 0, 'noncanonical_bb': 1}, extras
    # Non-vacuity: the dropped row existed, so counting it would add a third key.
    assert sum(1 for r in rows if 'MSE' in r) == 1

def test_label_multiset_mismatch_is_rejected(tmp_path):
    '''Different LABELS in name and array means no column can be attributed,
    so the bucket is refused rather than guessed at.'''
    with pytest.raises(ValueError, match='aa_bucket_parts'):
        load_bucket_counts(
            _make_bucket(str(tmp_path), 'CG_corrupt', 'ASP_bb.npz', ['GLU', 'bb'],
                         [('GLU', 'GLY')]), bb_mode='per-residue')

def test_per_residue_mode_sums_cluster_num_parents_not_row_count(tmp_path):
    '''Per-residue attribution must sum cluster_num_parents per row, not count
    rows: two ASP_GLY-bb clusters with parent counts [1, 5] must report 6, not
    2. FALSIFIER: a reader that does `+= 1` per row returns 2.'''
    frag_dir = os.path.join(str(tmp_path), 'CG_parents_bb')
    npz_dir = os.path.join(frag_dir, 'nr_vdgs', '1')
    os.makedirs(os.path.join(npz_dir, 'pos'))
    np.savez(os.path.join(npz_dir, 'pos', 'ASP_bb.npz'),
             aa_bucket_parts=np.asarray(['ASP', 'bb'], dtype='U4'),
             cluster_id=np.arange(1, 3, dtype=np.int32),
             cluster_num_parents=np.asarray([1, 5], dtype=np.int32),
             nr_scrr_resname=np.asarray([('ASP', 'GLY'), ('ASP', 'GLY')], dtype='U4'))
    with open(os.path.join(frag_dir, 'CG_parents_bb_log'), 'w') as fh:
        fh.write('Job completed.\n')
    counts, _ = load_bucket_counts(npz_dir, bb_mode='per-residue')
    assert counts == {'ASP_GLY-bb': 6}, counts
    assert counts['ASP_GLY-bb'] != 2, 'counted rows instead of summing parents'

def test_bb_mode_off_skips_the_bucket_entirely(tmp_path):
    '''off must not fall through to the undeconvoluted count, which emits a
    raw 'ASP_bb' label that no prior covers.'''
    counts, extras = load_bucket_counts(
        _make_bucket(str(tmp_path), 'CG_off', 'ASP_bb.npz', ['ASP', 'bb'],
                     [('ASP', 'GLY'), ('ASP', 'TRP')]), bb_mode='off')
    assert counts == {}, counts
    assert extras == {'X': 0, 'noncanonical_bb': 0}, extras
